version: "3.6"

services:

  app:
    build: .
    tty: true
    depends_on:
      - db

  db:
    image: docker-io.docker.itcm.oneadr.net/postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "weather"
